# This file was generated by GoReleaser. DO NOT EDIT.
cask "breadboard" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/dangernoodle-io/breadboard/releases/download/v#{version}/breadboard_#{version}_darwin_amd64.zip"
      sha256 "689395b347b3a30e8edfd52dcfc469bd1185919e5285f49ee66b281ee3111d35"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/breadboard/releases/download/v#{version}/breadboard_#{version}_darwin_arm64.zip"
      sha256 "6c80492f8daf44210860646fcf58cdac135be2c5d341e5291ece1c8c341cdc65"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangernoodle-io/breadboard/releases/download/v#{version}/breadboard_#{version}_linux_amd64.tar.gz"
      sha256 "3334f27766640f96a6c42f7bc18451c12b7ab945cd7155e5bf56e76b7f91dcf9"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/breadboard/releases/download/v#{version}/breadboard_#{version}_linux_arm64.tar.gz"
      sha256 "56372040d79fb4aeb89ea3a30a1adc75c97d47130bae217edc38db04aa6045ee"
    end
  end

  name "breadboard"
  desc "Embedded development MCP server (serial, ESP-IDF, decode)"
  homepage "https://github.com/dangernoodle-io/breadboard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "breadboard"

  # No zap stanza required

end
