# This file was generated by GoReleaser. DO NOT EDIT.
cask "espidf-tools" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/dangernoodle-io/espidf-tools/releases/download/v#{version}/espidf-tools_#{version}_darwin_amd64.zip"
      sha256 "7ee3e5ad713f911b6eb9e4f19a4067cd33c061524387f472e0e02652f7f5a6f6"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/espidf-tools/releases/download/v#{version}/espidf-tools_#{version}_darwin_arm64.zip"
      sha256 "ca31322b3698017d3e2d724a85dad9cff4914231fa08cb452244ad3502b9a638"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangernoodle-io/espidf-tools/releases/download/v#{version}/espidf-tools_#{version}_linux_amd64.tar.gz"
      sha256 "2b5f23374eee4b1f958af8396b18a3f3fad8ec1bf65e85f61a31d72a95619460"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/espidf-tools/releases/download/v#{version}/espidf-tools_#{version}_linux_arm64.tar.gz"
      sha256 "0ce7ae1bf810d89e46ce70e39e27050137ff5ca975d3262d304441c63d908269"
    end
  end

  name "espidf-tools"
  desc "ESP-IDF developer tools (decode, MCP server)"
  homepage "https://github.com/dangernoodle-io/espidf-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "espidf-tools"

  # No zap stanza required

end
