# This file was generated by GoReleaser. DO NOT EDIT.
cask "espidf-tools" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/dangernoodle-io/espidf-tools/releases/download/v#{version}/espidf-tools_#{version}_darwin_amd64.zip"
      sha256 "93d31b326ebfa43639a3085284a9c8b2eb9dbe2e81fbe248be947959e9e121b6"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/espidf-tools/releases/download/v#{version}/espidf-tools_#{version}_darwin_arm64.zip"
      sha256 "cfbc748f65ed8e5d818ef555627a23f19d3d388810630687f7631c1343c0eda4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangernoodle-io/espidf-tools/releases/download/v#{version}/espidf-tools_#{version}_linux_amd64.tar.gz"
      sha256 "e7517f78ec2d2196d368a6cf8c5d34ce05cb7dce4f619c5cf3cf17da90b711ed"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/espidf-tools/releases/download/v#{version}/espidf-tools_#{version}_linux_arm64.tar.gz"
      sha256 "1c109780d39a6632a1d078513af50019fa4818117bedb53d4b9eb3c4de43bb57"
    end
  end

  name "espidf-tools"
  desc "ESP-IDF developer tools (decode, MCP server)"
  homepage "https://github.com/dangernoodle-io/espidf-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "espidf-tools"

  # No zap stanza required

end
