# This file was generated by GoReleaser. DO NOT EDIT.
cask "ouroboros" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "82bfc341cf9015e75bc3dcace4cfe014f48b006e6421b84251786bddb89fed1b"
      url "https://github.com/dangernoodle-io/ouroboros/releases/download/v#{version}/ouroboros_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb6ad4918b024bd36ffaa1f0c545c65b082b5deb226e07a61e596acae2394b77"
      url "https://github.com/dangernoodle-io/ouroboros/releases/download/v#{version}/ouroboros_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f9f43c5182fe07b106aa8adb76c41e5472a3fab996bed9927d0dc25ab1b4fb2c"
      url "https://github.com/dangernoodle-io/ouroboros/releases/download/v#{version}/ouroboros_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd9be9d5b32fea56ce3acc5567547905aff8f811e664fac1edcec1421ee1cbdc"
      url "https://github.com/dangernoodle-io/ouroboros/releases/download/v#{version}/ouroboros_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ouroboros"
  desc "MCP server for project knowledge base"
  homepage "https://github.com/dangernoodle-io/ouroboros"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ouroboros"

  # No zap stanza required

end
