# This file was generated by GoReleaser. DO NOT EDIT.
cask "ouroboros" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/dangernoodle-io/ouroboros/releases/download/v#{version}/ouroboros_#{version}_darwin_amd64.zip"
      sha256 "19e23f6ff2fa1c7be28511fce7347bd330d13ac55d960548eacd77c08514b67e"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/ouroboros/releases/download/v#{version}/ouroboros_#{version}_darwin_arm64.zip"
      sha256 "4649015c574d897a777cd7517adf12e1987282685334d9726db79ccf116cf17a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangernoodle-io/ouroboros/releases/download/v#{version}/ouroboros_#{version}_linux_amd64.tar.gz"
      sha256 "947f09a324fd1ecccbf3c8c458c768d976d888aaa0f52d9e357fc47599983178"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/ouroboros/releases/download/v#{version}/ouroboros_#{version}_linux_arm64.tar.gz"
      sha256 "09ff450b6520d10f1fea1c70d57843b3d079f337bfad56d936dabe875c04e7ab"
    end
  end

  name "ouroboros"
  desc "MCP server for project knowledge base"
  homepage "https://github.com/dangernoodle-io/ouroboros"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ouroboros"

  # No zap stanza required

end
