# This file was generated by GoReleaser. DO NOT EDIT.
cask "ouroboros" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/dangernoodle-io/ouroboros/releases/download/v#{version}/ouroboros_#{version}_darwin_amd64.zip"
      sha256 "96023088423a418f61b80e758b3d9b638c04bbe46031d79f1bdfabac8735c0d1"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/ouroboros/releases/download/v#{version}/ouroboros_#{version}_darwin_arm64.zip"
      sha256 "4b57034a5a3f156da3b2ab474f5a1ae8874bdd4eec8cc22e7c8a5bc9a9da70f9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangernoodle-io/ouroboros/releases/download/v#{version}/ouroboros_#{version}_linux_amd64.tar.gz"
      sha256 "2e056ce31e693e945125d998761de429138f5db5af41e5a9b75c18f1f8433d42"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/ouroboros/releases/download/v#{version}/ouroboros_#{version}_linux_arm64.tar.gz"
      sha256 "20cf7a9139951dc9956d0e1f4000e5c4bcb98d24a486bafa604ecd6541d2f9aa"
    end
  end

  name "ouroboros"
  desc "MCP server for project knowledge base"
  homepage "https://github.com/dangernoodle-io/ouroboros"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ouroboros"

  # No zap stanza required

end
