# This file was generated by GoReleaser. DO NOT EDIT.
cask "pogopin" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/dangernoodle-io/pogopin/releases/download/v#{version}/pogopin_#{version}_darwin_amd64.zip"
      sha256 "887122dca39169b754325669907c4d86138fa05602d9043e86691dd008e22195"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/pogopin/releases/download/v#{version}/pogopin_#{version}_darwin_arm64.zip"
      sha256 "823a35437b40337cc5726797f7a4a6e9da59d982d504419fc1a25d30a1aefcd5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangernoodle-io/pogopin/releases/download/v#{version}/pogopin_#{version}_linux_amd64.tar.gz"
      sha256 "f24f674d0607908e7d487e9466baec19c7a8b4cde77b86a92e73950c1f7860bd"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/pogopin/releases/download/v#{version}/pogopin_#{version}_linux_arm64.tar.gz"
      sha256 "b49503e4062f4097f3f792919b811def44643276baf72b4dd92a94dce82bac6f"
    end
  end

  name "pogopin"
  desc "Embedded development MCP server (serial, ESP-IDF, decode)"
  homepage "https://github.com/dangernoodle-io/pogopin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pogo"

  # No zap stanza required

end
