# This file was generated by GoReleaser. DO NOT EDIT.
cask "pogopin" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "f25834563e30198043f426682f8985d10ac31d3f2a9faca4ad5cf4b1c5cdd833"
      url "https://github.com/dangernoodle-io/pogopin/releases/download/v#{version}/pogopin_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "05b818617aa77c921d80ab8fc90289b7ce23db3ff08ae4c0f973cba61765fb9a"
      url "https://github.com/dangernoodle-io/pogopin/releases/download/v#{version}/pogopin_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "463a8f8e92d5b769365d9874a86fcf8617dcac88d279afc6b466c970008d211b"
      url "https://github.com/dangernoodle-io/pogopin/releases/download/v#{version}/pogopin_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2eb8ceaa35560a2462d52a3aced42159d5ba6b5d1366d4879830f35cec381e81"
      url "https://github.com/dangernoodle-io/pogopin/releases/download/v#{version}/pogopin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pogopin"
  desc "Embedded development MCP server (serial, ESP-IDF, decode)"
  homepage "https://github.com/dangernoodle-io/pogopin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pogo"

  # No zap stanza required

end
