# This file was generated by GoReleaser. DO NOT EDIT.
cask "pogopin" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "2e38c08a7ac9a629ce79ae5a0b12d8cea4fc3c72397c8aba72130c0e08da56e3"
      url "https://github.com/dangernoodle-io/pogopin/releases/download/v#{version}/pogopin_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "48f0c10b2311c59b2d5514113f7f3359ee1493f0c4d7830d8dfadd79f4f75632"
      url "https://github.com/dangernoodle-io/pogopin/releases/download/v#{version}/pogopin_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "13dee9c9f0a09695c906598a08d957b4b27ae5aa3996aec889c125d318083d8f"
      url "https://github.com/dangernoodle-io/pogopin/releases/download/v#{version}/pogopin_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dafabf5c24cbb1ae92bc3d33303e88d930772c3e7fc303ba0dac9d5152dc6de3"
      url "https://github.com/dangernoodle-io/pogopin/releases/download/v#{version}/pogopin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pogopin"
  desc "Embedded development MCP server (serial, ESP-IDF, decode)"
  homepage "https://github.com/dangernoodle-io/pogopin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pogo"

  # No zap stanza required

end
