# This file was generated by GoReleaser. DO NOT EDIT.
cask "serial-io-mcp" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/dangernoodle-io/serial-io-mcp/releases/download/v#{version}/serial-io-mcp_#{version}_darwin_amd64.zip"
      sha256 "b997ed21a87bc3ec353a43a519acea1ce5c40f636c31052b2c77537475210fe6"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/serial-io-mcp/releases/download/v#{version}/serial-io-mcp_#{version}_darwin_arm64.zip"
      sha256 "417d39eb692c28b96414c1a7a5cff42d1da630cc2d45b6bc8d3bd3fff89a7a82"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangernoodle-io/serial-io-mcp/releases/download/v#{version}/serial-io-mcp_#{version}_linux_amd64.tar.gz"
      sha256 "874435a98f71b976af8e965ba719e07cc7989e8b8c23135d51e06dc94f797566"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/serial-io-mcp/releases/download/v#{version}/serial-io-mcp_#{version}_linux_arm64.tar.gz"
      sha256 "7f9a6617b09e74250adb4f52810b4ee4a72e37ddbf441b173ae32c4516f55f92"
    end
  end

  name "serial-io-mcp"
  desc "MCP server for serial port monitoring and control"
  homepage "https://github.com/dangernoodle-io/serial-io-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "serial-io-mcp"

  # No zap stanza required

end
