# This file was generated by GoReleaser. DO NOT EDIT.
cask "serial-io-mcp" do
  version "0.5.1"

  on_macos do
    on_intel do
      url "https://github.com/dangernoodle-io/serial-io-mcp/releases/download/v#{version}/serial-io-mcp_#{version}_darwin_amd64.zip"
      sha256 "4578e8e6f8dd277fc39eb12b10ea1086bcd7cb5757f44da427f46e8583388701"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/serial-io-mcp/releases/download/v#{version}/serial-io-mcp_#{version}_darwin_arm64.zip"
      sha256 "7c59715a03273caac34954e63c9401f6aa32b7a1aa6e51d32c8a74795d94b669"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangernoodle-io/serial-io-mcp/releases/download/v#{version}/serial-io-mcp_#{version}_linux_amd64.tar.gz"
      sha256 "0b490bb8450accf44bfba215114d71690c6a929f17bb69246ace8b8e8142662e"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/serial-io-mcp/releases/download/v#{version}/serial-io-mcp_#{version}_linux_arm64.tar.gz"
      sha256 "d9125e8c0605fa03607c808aa22096e48ca9e33d709bf9f69a2e10300d1cb187"
    end
  end

  name "serial-io-mcp"
  desc "MCP server for serial port monitoring and control"
  homepage "https://github.com/dangernoodle-io/serial-io-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "serial-io-mcp"

  # No zap stanza required

end
