# This file was generated by GoReleaser. DO NOT EDIT.
cask "serial-io-mcp" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/dangernoodle-io/serial-io-mcp/releases/download/v#{version}/serial-io-mcp_#{version}_darwin_amd64.zip"
      sha256 "c858e7a9fde1e5519a192816c9b327c756b94224e29c9838eb4d6b6608cd1ffb"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/serial-io-mcp/releases/download/v#{version}/serial-io-mcp_#{version}_darwin_arm64.zip"
      sha256 "f174d16fa7d444f1cda6a1e002404b467c99d720637d357d26a1ef95ef559f5b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangernoodle-io/serial-io-mcp/releases/download/v#{version}/serial-io-mcp_#{version}_linux_amd64.tar.gz"
      sha256 "70961082098c529c59e60d5bd6ca87133e2d33729d39e9e3efa5189d6a8dda5d"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/serial-io-mcp/releases/download/v#{version}/serial-io-mcp_#{version}_linux_arm64.tar.gz"
      sha256 "07ff4c57c914fa7d9e84fe263310ed54d7053542882a3368f35e83ea648c19a8"
    end
  end

  name "serial-io-mcp"
  desc "MCP server for serial port monitoring and control"
  homepage "https://github.com/dangernoodle-io/serial-io-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "serial-io-mcp"

  # No zap stanza required

end
