# This file was generated by GoReleaser. DO NOT EDIT.
cask "terranoodle" do
  name "terranoodle"
  desc "Useful cli tools for OpenTofu, Terraform, and Terragrunt"
  homepage "https://github.com/dangernoodle-io/terranoodle"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terranoodle"

  on_macos do
    on_intel do
      url "https://github.com/dangernoodle-io/terranoodle/releases/download/v#{version}/terranoodle_#{version}_darwin_amd64.zip"
      sha256 "afa8b2679e63795e25d891ae8c8eb66e5df3316e1f611e6c6921aec26a75e2d3"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/terranoodle/releases/download/v#{version}/terranoodle_#{version}_darwin_arm64.zip"
      sha256 "f726fdddfbec7bef03d50455830377c3a5594b3fe379f2af29f7239a6b179ea4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangernoodle-io/terranoodle/releases/download/v#{version}/terranoodle_#{version}_linux_amd64.tar.gz"
      sha256 "ff777866c067ca7d3cfb64707b4f0741850b2dfcf4dd6c4cf3610f3f73202901"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/terranoodle/releases/download/v#{version}/terranoodle_#{version}_linux_arm64.tar.gz"
      sha256 "6e1e7b2db14a4dd09506e675458b455cd652d2236701afa4020fd3ac944dd77a"
    end
  end

  # No zap stanza required
end
