# This file was generated by GoReleaser. DO NOT EDIT.
cask "terranoodle" do
  name "terranoodle"
  desc "Useful cli tools for OpenTofu, Terraform, and Terragrunt"
  homepage "https://github.com/dangernoodle-io/terranoodle"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terranoodle"

  on_macos do
    on_intel do
      url "https://github.com/dangernoodle-io/terranoodle/releases/download/v#{version}/terranoodle_#{version}_darwin_amd64.zip"
      sha256 "84f10b6b34ad78c30398cf7b23a4d360e13472e213213e8f8657d4a5ce5aa22b"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/terranoodle/releases/download/v#{version}/terranoodle_#{version}_darwin_arm64.zip"
      sha256 "c9ae40940e51bc01637e932c0fae8451f409263c115cd9a9ee35538fb9105929"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangernoodle-io/terranoodle/releases/download/v#{version}/terranoodle_#{version}_linux_amd64.tar.gz"
      sha256 "136b310d5ffd5401c0872f9c431dc982ad336126a9bfef0e1a6cd7edda370b97"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/terranoodle/releases/download/v#{version}/terranoodle_#{version}_linux_arm64.tar.gz"
      sha256 "85c154cad6135007a067d842df48108e3410a8c107ae10dfac0c8469d7705f62"
    end
  end

  # No zap stanza required
end
