# This file was generated by GoReleaser. DO NOT EDIT.
cask "terranoodle" do
  name "terranoodle"
  desc "Useful cli tools for OpenTofu, Terraform, and Terragrunt"
  homepage "https://github.com/dangernoodle-io/terranoodle"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terranoodle"

  on_macos do
    on_intel do
      url "https://github.com/dangernoodle-io/terranoodle/releases/download/v#{version}/terranoodle_#{version}_darwin_amd64.zip"
      sha256 "bda742aa9faab891d9d279ef37639f094492d45d2fcdaabad6dd265edc967d08"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/terranoodle/releases/download/v#{version}/terranoodle_#{version}_darwin_arm64.zip"
      sha256 "49cc783689b423d70d32bd27ef075adbcf64c792f7b8eb5c325fcf3e5285a90b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dangernoodle-io/terranoodle/releases/download/v#{version}/terranoodle_#{version}_linux_amd64.tar.gz"
      sha256 "dbf260a626c440278d97679f0410993573c627ff8a177a4021c4b5acd46670e8"
    end
    on_arm do
      url "https://github.com/dangernoodle-io/terranoodle/releases/download/v#{version}/terranoodle_#{version}_linux_arm64.tar.gz"
      sha256 "6ed2218d272edba4fefc94ece1688b3ab3bc043c74ed352b54b825f9ef980ac1"
    end
  end

  # No zap stanza required
end
